# Generated by Django 3.0.7 on 2020-09-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsforcheckout',
            name='business_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
