# Generated by Django 3.0.7 on 2020-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_productsforcheckout_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_amount',
            field=models.IntegerField(default=0),
        ),
    ]
