# Generated by Django 3.0.7 on 2020-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_profile_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsforcheckout',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
