# Generated by Django 3.0.7 on 2020-10-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_profile_is_complete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='nearest_landmark',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
