# Generated by Django 3.0.7 on 2020-10-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20201011_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_bought_from', models.CharField(blank=True, max_length=50)),
                ('date_bought', models.DateField(auto_now=True)),
                ('product', models.CharField(blank=True, max_length=50)),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('address_of_site', models.CharField(blank=True, max_length=50)),
                ('address_of_business_bought_from', models.CharField(blank=True, max_length=50)),
                ('quantity_ordered', models.PositiveIntegerField(default=0)),
                ('price_per_quantity', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.Profile')),
            ],
        ),
    ]
