# Generated by Django 3.0.7 on 2020-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
