# Generated by Django 3.1.4 on 2020-12-22 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
